# S03 T02: Estructura d'una Matriu

## Nivell 1

Treballem els conceptes de l'estructura d'una matriu, dimensió, eixos i la vectorització que ens permet reduir l'ús de for loops en operacions aritmètiques o matemàtiques.

### Exercici 1

Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.

In [78]:
import numpy as np
arr = np.array([1, 20, 18, 22, 15, 19, 3, 12], dtype="int64")
print(arr)

[ 1 20 18 22 15 19  3 12]


In [79]:
print(arr.ndim)

1


La dimensió de la matriu es 1

In [80]:
print(arr.dtype)

int64


La forma de la matriu es int64

### Exercici 2

De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [81]:
import pandas as pd
import statistics
mitjà = arr.mean()
print(mitjà)

13.75


El valor mitjà de la matriu es 13.75

In [82]:
print(statistics.median(arr))

16.5


La mitjana de la matriu es 16.5

In [84]:
for x in arr:
  print(x-16.5)

-15.5
3.5
1.5
5.5
-1.5
2.5
-13.5
-4.5


### Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [85]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [26, 27, 28, 29, 30]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [26 27 28 29 30]]


In [86]:
np.amax(arr2)

30

 El valor màxim de la matriu es 30

In [87]:
np.amax(arr2, axis = 0)

array([26, 27, 28, 29, 30])

Els valors màxims dels eixos verticals són 26, 27, 28, 29 y 30

In [88]:
np.amax(arr2, axis = 1)

array([ 5, 10, 15, 20, 30])

Els valors màxims dels eixos horizontals són 5, 10, 15, 20 y 30

## Nivell 2

Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask.

### Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

*Exemple 1*

In [13]:
from numpy import array
a = array([[ 0.0,  0.0,  0.0],
           [10.0, 10.0, 10.0],
           [20.0, 20.0, 20.0],
           [30.0, 30.0, 30.0]])
b = array([1.0, 2.0, 3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

Exemple 2

In [72]:
a = array([[ 5.0,  7.0,  9.0, 11.0],
           [10.0, 14.0, 18.0, 22.0],
           [20.0, 28.0, 36.0, 44.0],
           [40.0, 56.0, 72.0, 88.0]])
b = array([6.0, 7.0, 8.0, 9.0])
a * b

array([[ 30.,  49.,  72.,  99.],
       [ 60.,  98., 144., 198.],
       [120., 196., 288., 396.],
       [240., 392., 576., 792.]])

Exemple 3

In [73]:
a = array([[ 5.0,  7.0,  9.0, 11.0],
           [10.0, 14.0, 18.0, 22.0],
           [20.0, 28.0, 36.0, 44.0],
           [40.0, 56.0, 72.0, 88.0]])
b = array([[6.0, 7.0, 8.0, 9.0],
          [6.0, 7.0, 8.0, 9.0],
          [6.0, 7.0, 8.0, 9.0],
          [6.0, 7.0, 8.0, 9.0]])
a + b

array([[11., 14., 17., 20.],
       [16., 21., 26., 31.],
       [26., 35., 44., 53.],
       [46., 63., 80., 97.]])

Exemple 4 (con error)

In [74]:
a = array([[ 5.0,  7.0,  9.0, 11.0, 13.0],
           [10.0, 14.0, 18.0, 22.0, 26.0],
           [20.0, 28.0, 36.0, 44.0, 52.0],
           [40.0, 56.0, 72.0, 88.0, 104.0]])
b = array([[6.0, 7.0, 8.0, 9.0],
          [6.0, 7.0, 8.0, 9.0],
          [6.0, 7.0, 8.0, 9.0],
          [6.0, 7.0, 8.0, 9.0]])
a + b

ValueError: operands could not be broadcast together with shapes (4,5) (4,4) 

### Exercici 5

Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [89]:
arr3 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [26, 27, 28, 29, 30]])
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [26 27 28 29 30]]


In [90]:
horizontal = ((arr3[1, 0])+(arr3[1, 1])+(arr3[1, 2])+(arr3[1, 3])+(arr3[1, 4]))
print(horizontal)

40


In [91]:
vertical = ((arr3[0, 0])+(arr3[1, 0])+(arr3[2, 0])+(arr3[3, 0])+(arr3[4, 0]))
print(vertical)

60


In [92]:
sumatotal = horizontal+vertical
print(sumatotal)

100


### Exercici 6

Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.
Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

In [67]:
import numpy.ma as ma
ma_arr = ma.masked_array(arr % 4 == 0)
print(ma_arr)

[[False False False  True False]
 [False False  True False False]
 [False  True False False False]
 [ True False False False  True]
 [False False  True False False]]


### Exercici 7

A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

In [71]:
arr[ma_arr]

array([ 4,  8, 12, 16, 20, 28])